config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  match 'organizers', to: 'pages#organizers',       via: 'get'
  match 'admin',      to: 'admin/organizers#index', via: 'get'
  
  get 'signout', to: 'sessions#destroy'
  get "/auth/:provider/callback", to: "sessions#create"

  resources :sessions,  only: [:create, :destroy]
  resources :resources, only: [:index, :show]

  resources :checkouts do
    collection do
      get :payment
    end
  end

  resources :events, only: [:index, :show, :new, :create, :edit, :destroy] do
    member do
      post :add_attendee
    end
  end

  resources :pages, only: [:index] do
    collection do
      get :organizers
    end
  end

  namespace :admin do
    resources :organizers, only: [:index]
  end

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendees
  has_many :users, through: :attendees

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :attendees
  has_many :events, through: :attendees

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider    = auth.provider
      user.uid         = auth.uid
      user.name        = auth.info.name
      user.email       = auth.info.email
      user.image       = auth.info.image
      user.save
    end
  end
end

app/controllers/admin/organizers_controller.rb
class Admin::OrganizersController < AdminController

  def index
    @event = Event.new
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize?

  private

  def authorize?
    unless current_user && current_user.admin == true
      redirect_to '/'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController

  def payment
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.new(event_params)

    if event.save!
      redirect_to admin_path
    end
  end

  def add_attendee
    event = Event.find(params[:id])

    if already_rsvpd?(event)
      redirect_to :back, alert: "You've already RSVP'd for #{event.title}."
    else
      attendee = Attendee.new
      attendee.event_id = event.id
      attendee.user_id = current_user.id
      attendee.save!

      event.attendees << attendee
      redirect_to :back, notice: "You have successfully RSVP'd for #{event.title}!"
    end
  end

  private

  def already_rsvpd?(event)
    event.attendees.any? {|a| a.user_id == current_user.id }
  end
  
  def event_params
    params.require(:event).permit( :title,
                                   :description,
                                   :location,
                                   :time
                                 )
  end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @event = Event.last
  end

  def organizers
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
  end

  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    user.save!
    session[:user_id] = user.id
    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    redirect_to :back, notice: "Signed out!"
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
end

app/views/admin/organizers/index.html.erb
<div class='container'>
<div class='panel'>
  <div class='panel-heading text-center'>
    <h1>ADMIN DASHBOARD</h1>
  </div>
</div>
<div class='col-md-4 col-md-offset-4'>
<h3>Create a new event</h3>
<%= form_for @event do |f| %>

  <%= f.text_field :title, class: 'form-control', placeholder: 'title' %>
  <%= f.text_area :description,  class: 'form-control' , placeholder: 'description' %>
  <%= f.text_field :location,  class: 'form-control', placeholder: '1500 Blake St. Denver, CO' %>
  <%= f.datetime_select :time, :ampm => true, :minute_step => 15 %>
  <%= f.submit 'Create Event', class: 'btn btn-danger btn-block btn-create-event' %>
<% end %>
</div>
</div>

app/views/checkouts/payment.html.erb
<div class='container'>
  <div class='panel'>
    <div class='panel-heading'>
      <h1>PAYMENT</h1>
    </div>
  </div>
  <div class='form-horizontal'>

  </div>
</div>

app/views/events/index.html.erb
<div class='container'>
<div class='panel'>
  <div class='panel-heading text-center'>
    <h1>EVENTS</h1>
  </div>
</div>
<div class='col-md-4 col-md-offset-4'>
<% @events.each do |e| %>
  <div class='thumbnail' id="tb-<%= e.id %>">
    <div class='caption cap-top'>
      <h2><%= e.title %></h2>
      <p style='color: white; font-weight: 100; font-size: 136px'><%= e.time.strftime('%d') %></p>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class='panel'>
        <div class='panel-heading' id='headingOne'>
          <h5>
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            DETAILS
            </a>
          </h5>
        </div>
        <div id="collapseOne" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p><%= "WHEN : #{e.time.strftime('%A, %d %b %l:%M %p')}" %></p>
        <p><%= "WHERE : #{e.location}" %></p>
        <p>DESCRIPTION :</p>
        <p><%= e.description %></p>
      </div>
    </div>
      </div>
    </div>
  </div>
<% unless current_user %>
  <%= link_to 'sign in with twitter', 'auth/twitter', class: 'btn btn-block btn-twitter' %>
  <%= link_to 'sign in with github', 'auth/github', class: 'btn btn-block btn-github' %>
<% else %>
  <%= button_to 'RSVP', add_attendee_event_path(current_user, event_id: e.id), class: 'btn btn-block btn-rsvp' %>
<% end %>
<% end %>
</div>
</div>

app/views/events/show.html.erb
<div class='container'>
<div class='panel'>
  <div class='panel-heading text-center'>
    <h1><%= @event.title %></h1>
  </div>
</div>
<div class='col-md-4 col-md-offset-4'>
  <div class='thumbnail'>
    <div class='caption cap-top'>
      <p style='color: white; font-weight: 100; font-size: 136px'><%= @event.time.strftime('%d') %></p>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class='panel'>
        <div class='panel-heading' id='headingOne'>
          <h5>
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            DETAILS
            </a>
          </h5>
        </div>
        <div id="collapseOne" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p><%= "WHEN : #{@event.time.strftime('%A, %d %b %l:%M %p')}" %></p>
        <p><%= "WHERE : #{@event.location}" %></p>
        <p>DESCRIPTION :</p>
        <p><%= @event.description %></p>
      </div>
    </div>
      </div>
    </div>
  </div>
<% unless current_user %>
  <%= link_to 'sign in with twitter', 'auth/twitter', class: 'btn btn-block btn-twitter' %>
  <%= link_to 'sign in with github', 'auth/github', class: 'btn btn-block btn-github' %>
<% else %>
  <%= button_to 'RSVP', add_attendee_event_path(current_user, event_id: @event.id), class: 'btn btn-block btn-rsvp' %>
<% end %>
</div>
</div>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">NodeBots Colorado</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/events">Events</a></li>
            <li><a href="/organizers">Organizers</a></li>
            <li><a href="/resources">Resources</a></li>
          </ul>
          <% if current_user %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Welcome #{current_user.name}!", '#' %></li>
              <li><%= link_to "Sign Out", signout_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nodebots</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class='alert-background text-center'>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%=type%>">
        <%= message%>
      </div>
    <% end %>
  </div>
    
  <%= yield %>
</body>
</html>

app/views/pages/index.html.erb
<div class='container'>
  <div class='panel'>
   <div class='panel-heading text-center'>
     <h1>NodeBots Colorado</h1>
   </div>
  </div>
  <div class='col-md-4 col-md-offset-4'>
    <div class='thumbnail'>
      <div class='caption cap-top'>
        <h2><%= @event.title %></h2>
        <p style='color: white; font-weight: 100; font-size: 136px'><%= @event.time.strftime('%d') %></p>
      </div>
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class='panel'>
          <div class='panel-heading' id='headingOne'>
            <h5>
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              DETAILS
              </a>
            </h5>
          </div>
          <div id="collapseOne" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
          <p><%= "WHEN : #{@event.time.strftime('%A, %d %b %l:%M %p')}" %></p>
          <p><%= "WHERE : #{@event.location}" %></p>
          <p>DESCRIPTION :</p>
          <p><%= @event.description %></p>
        </div>
      </div>
        </div>
      </div>
    </div>
  <% unless current_user %>
    <%= link_to 'sign in with twitter', 'auth/twitter', class: 'btn btn-block btn-twitter' %>
    <%= link_to 'sign in with github', 'auth/github', class: 'btn btn-block btn-github' %>
  <% else %>
    <%= button_to 'RSVP', add_attendee_event_path(current_user, event_id: @event.id), class: 'btn btn-block btn-rsvp' %>
  <% end %>
  </div> 
</div>

app/views/pages/organizers.html.erb
<div class='container'>
  <div class='panel'>
    <div class='panel-heading text-center'>
      <h1>ORGANIZERS</h1>
    </div>
  </div>
  <div class='col-md-4 col-md-offset-4'>
    <div class='thumbnail'>
      <img src="https://pbs.twimg.com/profile_images/565704816412745728/eLljaYJG.jpeg">
      <div class='caption'>
        <h3>Steve Kinney</h3>
        <p><a href="http://turing.io/">Turing</a> Instructor and JavaScript guru.</p>
        <a href="https://twitter.com/stevekinney">@stevekinney</a>
      </div>
    </div>
    <div class='thumbnail'>
      <img src="https://pbs.twimg.com/profile_images/528221635300454400/e7s22KZI.jpeg">
      <div class='caption'>
        <h3>Corey Davis</h3>
        <p><a href="http://turing.io/">Turing</a> Alumni and web developer at Commerce Kitchen.</p>
        <a href="https://twitter.com/spanulate">@spanulate</a>
      </div>
    </div>
    <div class='thumbnail'>
      <img src="https://pbs.twimg.com/profile_images/476446734587928577/8HRk-oEm.jpeg">
      <div class='caption'>
        <h3>Alan Smith</h3>
        <p><a href="http://turing.io/">Turing</a> Alumni and web developer at LivingSocial.</p>
        <a href="https://twitter.com/alan_b_smith">@alan_b_smith</a>
      </div>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<div class='container'>
  <div class='panel'>
    <div class='panel-heading text-center'>
      <h1>RESOURCES</h1>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
show.html.erb